### ISSUE TITLE
Cannot access logs on the CLI

### ISSUE THREAD

**Issue by Enriquito** [suryamodulus/pm2-webui#1]
When I start the web UI. I cannot open my logs anymore on the CLI. Is the service blocking out this output? 

`~/pm2-webui/src$ pm2 logs
node[4273]: pthread_create: Resource temporarily unavailable`

**Comment by suryamodulus** [comment]
@Enriquito Actually its not supposed block the output. I've tested in my server. can you provide some context ? 
One possible explanation might be that, size of log file is too large and is unable to fit into memory.
