### ISSUE TITLE
Start Process

### ISSUE THREAD

**Issue by lmangani** [suryamodulus/pm2-webui#3]
Great project you have here! Thanks for your work.

Do you have any plans to add a hook for pm2.start?

**Comment by suryamodulus** [comment]
@lmangani I'm working on building a better tool on top of pm2-webui with webhooks, auto-deployment and more. Hopefully I'll try to implement that feature there.

**Comment by lmangani** [comment]
@suryamodulus let us know where and we'll join & contribute!
